### PR TITLE
EntityOperationEvent: fixes fatal error when no operations have defined.

### PR DESCRIPTION
**Pull request by Ambient-Impact**
Bit of a surprise when I went to ```admin/content```. ;)

### CODE REVIEW

**Comment by pdenooijer** [comment]
Yeah still have to test it, please rebase unto the last commit of pdenooijer:8.x-2.x branch

**Comment by pdenooijer** [comment]
Next 😁

**Comment by pdenooijer** [comment]
@Ambient-Impact any thoughts about this?
https://github.com/pdenooijer/hook_event_dispatcher/issues/97

**Comment by Ambient-Impact** [comment]
Let me know if I'm jumping the gun a bit, since you're still in the process of updating stuff. Started work on a new event and wanted to get these out of the way.

**Comment by pdenooijer** [comment]
Nope not at all, your helping me which is great and really appreciated 👍. Just make sure if you wanna change stuff around to make an issue first so we can discuss stuff in advance 🙂.

**Comment by Ambient-Impact** [comment]
Will do!

**Pull request merged**
