### PR TITLE
Merge duplicate field formatter and widget third-party settings code

### PR DESCRIPTION
**Pull request by Ambient-Impact**
See issue #103 and PRs #113 and #114.

### CODE REVIEW

**Comment by Ambient-Impact** [comment]
I really should have checked that the rebase was alright before opening this. 😅

**Review by pdenooijer — APPROVED** [review]

**Comment by pdenooijer** [comment]
Thnx 👍

**Comment by Ambient-Impact** [comment]
I'm genuinely surprised I didn't miss anything for you request changes on. 😛

**Comment by pdenooijer** [comment]
To keep it interesting 😉

**Pull request merged**
