### PR TITLE
Add status_messages preprocess event

### PR DESCRIPTION
**Pull request by DieterHolvoet**

### CODE REVIEW

**Review by pdenooijer — CHANGES_REQUESTED** [review]
Thanks for the PR 👍 

I am missing the tests for this event. You can have a look how the other preprocess events are tested, mostly copy paste anyway.

Also please rebase on the latest 8.x so the merge commit goes.

**Comment by pdenooijer** [comment]
@DieterHolvoet could you please add tests so I can merge your code 🙂

**Comment by DieterHolvoet** [comment]
@pdenooijer Checks are still failing, is there anything I can do about it?

**Comment by pdenooijer** [comment]
PHPMD gives errors about coupling and methods, currently not have much time. I'll try to come up with a solution next week, thanks for the effort 👍.

**Comment by pdenooijer** [comment]
Thanks, I'll fix the failings!

**Pull request merged**
