### PR TITLE
Add support for token hooks

### PR DESCRIPTION
**Pull request by epinxteren**

### CODE REVIEW

**Comment by robiningelbrecht** [comment]
Looks nice and clean! Thanks!
@pdenooijer can you merge this?

**Comment by pdenooijer** [comment]
@robiningelbrecht I'll have a look then I'll merge it 👍

**Comment by dmouse** [comment]
Maybe is the moment to add a composer.json file and define tokens in the `suggest` packages section

**Comment by pdenooijer** [comment]
@dmouse can you be more specific?

**Comment by dmouse** [comment]
One key in the composer is the suggested packages, this PR is about trigger events from the `token` module, but `Token` is not a requirement in `hook_event_dispatcher` module so We can put in the `composer.json` like a suggest package, for example:
```
{
  "name": "drupal/hook_event_dispatcher",
  "description": "Dispatches events for several drupal core hooks.",
  "type": "drupal-module",
  "license": "GPL-2.0+",
  "require-dev": {
    "drupal/core": "^8.2",
    "phpunit/phpunit": "^5.7",
    "drupal/coder": "^8.2",
    "phpmd/phpmd": "^2.6",
    "jakub-onderka/php-parallel-lint": "^0.9.2",
    "jakub-onderka/php-console-highlighter": "^0.3.2"
  },
  "autoload": {
    "psr-4": { "Drupal\\hook_event_dispatcher\\": "src/" }
  },
  "autoload-dev": {
    "psr-4": {
      "Drupal\\Tests\\hook_event_dispatcher\\": "tests/src/"
    }
  },
  "repositories": {
    "drupal": {
      "type": "composer",
      "url": "https://packages.drupal.org/8"
    }
  },
   "suggest": {
        "drupal/token": "Provides additional tokens not supported by core, as well as a UI for browsing tokens."
    }
}
```

**Comment by pdenooijer** [comment]
@dmouse good point, thanks for you input 👍!

**Comment by pdenooijer** [comment]
Ignored this PR at the end, as the changes are in #9.

**Pull request merged**
